Use `wit-vue-ui`
witnet/website pull request #435
Opened 2024-09-16 17:02 UTC by gabaldon

2024-09-19 09:06 UTC, Tommytrg requested changes

2024-09-19 09:06 UTC, Tommytrg commented on components/cards/BuildWithWitnet.vue
<table>
<tr>
<th> PR </th>
<th> Production </th>
</tr>
<tr>
<td>


### 
![image](https://github.com/user-attachments/assets/57770261-708c-4765-8b69-315f87ddc90c)

</td>
<td>

![image](https://github.com/user-attachments/assets/bc873a97-76a6-4097-9e49-e4b12a13cce0)

</td>
</tr>
</table>

2024-09-19 09:06 UTC, Tommytrg commented on components/sections/CommunitySection.vue
<table>
<tr>
<th> PR </th>
<th> Production </th>
</tr>
<tr>
<td>

![image](https://github.com/user-attachments/assets/88951739-29e3-4aae-abff-0f30a5d37680)

</td>
<td>

![image](https://github.com/user-attachments/assets/b861bf6f-e41a-447d-a05f-39f81bd0c50e)

</td>
</tr>
</table>

2024-09-19 09:06 UTC, Tommytrg commented on components/FooterSection.vue
Add first letter capitalization and also underline links

<table>
<tr>
<th> PR </th>
<th> Production </th>
</tr>
<tr>
<td>

![image](https://github.com/user-attachments/assets/3217193f-ef10-4332-8a64-7747278b12e6)

</td>
<td>

![image](https://github.com/user-attachments/assets/8a6aa436-0753-4320-9845-977b32fc01e7)

</td>
</tr>
</table>

2024-09-19 09:50 UTC, gabaldon commented on components/FooterSection.vue
Where should I add first letter capitalization?

2024-09-19 16:46 UTC, Tommytrg reviewed
Could we add an space between the date and the first word?
![image](https://github.com/user-attachments/assets/86f8103f-4b9d-40ba-bcd5-c1191f9f6bfb)

2024-09-24 14:57 UTC, Tommytrg approved these changes

2024-09-24 15:02 UTC, merged